apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: avejlanjekar45/nginx-flask-mysql-backend
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-password
              mountPath: /run/secrets/db-password
              subPath: db-password
      volumes:
        - name: db-password
          secret:
            secretName: db-password

