pipeline {
    agent any

    environment {

        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = credentials('aws-account-id')

        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_REGISTRY_URL = "https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        AWS_CREDENTIALS = 'aws-ecr-credentials'
        ECR = 'ecr'

        BACKEND_IMAGE_DEV = 'app-backend-dev'
        BACKEND_IMAGE_QA = 'app-backend-qa'
        BACKEND_IMAGE_UAT = 'app-backend-uat'
        BACKEND_IMAGE_PROD = 'app-backend-prod'

        BUILD_CONTEXT = './backend'

        ECS_CLUSTER_DEV = 'app-ecs-cluster-dev'
        ECS_CLUSTER_QA = 'app-ecs-cluster-qa'
        ECS_CLUSTER_UAT = 'app-ecs-cluster-uat'
        ECS_CLUSTER_PROD = 'app-ecs-cluster-prod'

        ECS_SERVICE_DEV = 'app-backend-service-dev'
        ECS_SERVICE_QA = 'app-backend-service-qa'
        ECS_SERVICE_UAT = 'app-backend-service-uat'
        ECS_SERVICE_PROD = 'app-backend-service-prod'

        ECS_TASK_FAMILY_DEV = 'app-backend-dev'
        ECS_TASK_FAMILY_QA = 'app-backend-qa'
        ECS_TASK_FAMILY_UAT = 'app-backend-uat'
        ECS_TASK_FAMILY_PROD = 'app-backend-prod'

        TASK_DEFINITION = 'backend/task-definition.json'
    }

    parameters {

        choice(
            name: 'Environment',
            choices: ['dev', 'qa', 'uat', 'prod'],
            description: 'Select the Environment'
        )

        string(
            name: 'IMAGE_TAG',
            defaultValue: '',
            description: 'provide commit id'
        )
    }

    stages {

        stage('Dev - Build & Push') {

            when {
                expression {
                    params.Environment == 'dev'
                }
            }

            steps {

                script {

                    buildAndPush(
                        env.BACKEND_IMAGE_DEV,
                        env.BUILD_CONTEXT
                    )
                }
            }
        }


        stage('Dev - Deploy to ECS') {

            when {
                expression {
                    params.Environment == 'dev'
                }
            }

            steps {

                script {

                    deployToECS(
                        env.TASK_DEFINITION,
                        env.ECS_TASK_FAMILY_DEV,
                        env.ECS_SERVICE_DEV,
                        env.ECS_CLUSTER_DEV
                    )
                }
            }
        }

        stage('Promote Dev to QA') {

            when {
                expression {
                    params.Environment == 'qa'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.BACKEND_IMAGE_DEV,
                        env.BACKEND_IMAGE_QA
                    )
                }
            }
        }


        stage('QA - Deploy to ECS') {

            when {
                expression {
                    params.Environment == 'qa'
                }
            }

            steps {

                script {

                    deployToECS(
                        env.TASK_DEFINITION,
                        env.ECS_TASK_FAMILY_QA,
                        env.ECS_SERVICE_QA,
                        env.ECS_CLUSTER_QA
                    )
                }
            }
        }

        stage('Promote QA to UAT') {

            when {
                expression {
                    params.Environment == 'uat'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.BACKEND_IMAGE_QA,
                        env.BACKEND_IMAGE_UAT
                    )
                }
            }
        }


        stage('UAT - Deploy to ECS') {

            when {
                expression {
                    params.Environment == 'uat'
                }
            }

            steps {

                script {

                    deployToECS(
                        env.TASK_DEFINITION,
                        env.ECS_TASK_FAMILY_UAT,
                        env.ECS_SERVICE_UAT,
                        env.ECS_CLUSTER_UAT
                    )
                }
            }
        }

        stage('Approval for Prod Deployment') {

            when {
                expression {
                    params.Environment == 'prod'
                }
            }

            steps {

                input(
                    message: 'Promote UAT image to PROD?',
                    ok: 'Proceed'
                )
            }
        }

        stage('Promote UAT to PROD') {

            when {
                expression {
                    params.Environment == 'prod'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.BACKEND_IMAGE_UAT,
                        env.BACKEND_IMAGE_PROD
                    )
                }
            }
        }


        stage('PROD - Deploy to ECS') {

            when {
                expression {
                    params.Environment == 'prod'
                }
            }

            steps {

                script {

                    deployToECS(
                        env.TASK_DEFINITION,
                        env.ECS_TASK_FAMILY_PROD,
                        env.ECS_SERVICE_PROD,
                        env.ECS_CLUSTER_PROD
                    )
                }
            }
        }
    }

    post {

        always {

            deleteDir()
        }
    }
}

def buildAndPush(String imageRepository, String buildContext) {

    echo "Repository : ${imageRepository}"
    echo "Commit     : ${env.GIT_COMMIT}"


    def image = docker.build(
        "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}",
        buildContext
    )


    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        image.push()
    }


    echo "Image pushed successfully"

    echo "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}"
}

def promoteImage(String sourceImage, String targetImage) {

    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        docker.image(
            "${env.ECR_REGISTRY}/${sourceImage}:${params.IMAGE_TAG}"
        ).pull()
    }

    sh """
        docker tag \
        ${env.ECR_REGISTRY}/${sourceImage}:${params.IMAGE_TAG} \
        ${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}
    """

    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        docker.image(
            "${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}"
        ).push()
    }


    echo "Image promoted successfully"

    echo "${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}"
}

def deployToECS(String taskDefinitionFile, String taskFamily, String ecsService, String ecsCluster) {

    if(params.Environment == 'dev'){
        sh """
            sed -i 's/\\\${ENV}/${params.Environment}/g' ${taskDefinitionFile}
            sed -i 's/\\\${COMMIT_ID}/${env.GIT_COMMIT}/g' ${taskDefinitionFile}
        """
    }else{
        sh """
            sed -i 's/\\\${ENV}/${params.Environment}/g' ${taskDefinitionFile}
            sed -i 's/\\\${COMMIT_ID}/${params.IMAGE_TAG}/g' ${taskDefinitionFile}
        """
    }

    withCredentials([
        [$class: 'AmazonWebServicesCredentialsBinding',
         credentialsId: env.AWS_CREDENTIALS]
    ]){
        def taskRevision = sh(

            script: """
                aws ecs register-task-definition \
                    --cli-input-json file://${taskDefinitionFile} \
                    --region ${env.AWS_REGION} \
                    --query 'taskDefinition.revision' \
                    --output text
            """,
            returnStdout: true
        ).trim()

        sh """
            aws ecs update-service \
                --cluster ${ecsCluster} \
                --service ${ecsService} \
                --task-definition ${taskFamily}:${taskRevision} \
                --region ${env.AWS_REGION}
        """
    }
}