apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: avejlanjekar45/react-java-mysql-db-{{ENV}}:{{COMMITID}}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app3-cm
                  key: MYSQL_DATABASE

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app3-secret
                  key: MYSQL_ROOT_PASSWORD
