apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: avejlanjekar45/flask_webapp_avej:version-2
          ports:
            - containerPort: 8080
