def buildAndPushImage(String FRONTEND_IMAGE, String DH_CREDENTIALS, String Buildcontext){
    def frontend= docker.build("${FRONTEND_IMAGE}:${GIT_COMMIT}","${Buildcontext}")

    docker.withRegistry("${env.REGISTRY_URL}","${DH_CREDENTIALS}"){
        frontend.push()
    }
}

def promoteImage(String sourceImage, String targetImage, String source_DH_Credentials, String target_DH_Credentials){
    docker.withRegistry("${env.REGISTRY_URL}","${source_DH_Credentials}"){
        docker.image("${sourceImage}:${GIT_COMMIT}").pull()
    }

    sh "docker tag ${sourceImage}:${GIT_COMMIT} ${targetImage}:${GIT_COMMIT}"

    docker.withRegistry("${env.REGISTRY_URL}","${target_DH_Credentials}"){
        docker.image("${targetImage}:${GIT_COMMIT}").push()
    }
}

def deployToEks(String cluster_credentials, String namespace, String environment){
    withKubeConfig(credentialsId: "${cluster_credentials}", namespace: "${namespace}"){
        sh "echo deploying to ${namespace} namespace..."
        sh "sed -i -e 's/{{ENV}}/${environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/frontend-deployment.yml "
        sh 'kubectl apply -f kube/frontend-deployment.yml'
        sh 'kubectl apply -f kube/frontend-service.yml'
        sh 'kubectl apply -f kube/ingress.yml'
    }
}

pipeline{
    agent any

    environment{

        BUILD_CONTEXT='./frontend'

        FRONTEND_IMAGE_DEV= 'avejlanjekar45/employee-management-frontend-dev'
        FRONTEND_IMAGE_QA= 'avejlanjekar45/employee-management-frontend-qa'
        FRONTEND_IMAGE_UAT= 'avejlanjekar45/employee-management-frontend-uat'
        FRONTEND_IMAGE_PROD='avejlanjekar45/employee-management-frontend-prod'

        REGISTRY_URL= 'https://registry.hub.docker.com'

        DEV_DH_CREDENTIALS= 'dockerhub-credentials'
        QA_DH_CREDENTIALS= 'dockerhub-credentials'
        UAT_DH_CREDENTIALS= 'dockerhub-credentials'
        PROD_DH_CREDENTIALS= 'dockerhub-credentials'

        CLUSTER_CREDENTIALS= 'eks-kubeconfig'

        DEV_NS= 'employee-dev'
        QA_NS= 'employee-qa'
        UAT_NS= 'employee-uat'
        PROD_NS= 'employee-prod'
    }

    parameters{
        choice(
            name: 'Environment',
            choices: ["dev","qa","uat","prod"],
            description: "Select deployment environment"
        )
    }

    stages{

        stage("build & push"){
            when {
                expression{
                    params.Environment == "dev"
                }
            }
            steps{
                script{

                    // def frontend= docker.build("${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT}","./frontend")

                    // docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                    //     frontend.push()
                    // }

                    buildAndPushImage("${env.FRONTEND_IMAGE_DEV}","${env.DEV_DH_CREDENTIALS}", "${env.BUILD_CONTEXT}")

                    // withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-dev'){
                    //     sh 'echo deploying to employee-dev namespace...'
                    //     sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/frontend-deployment.yml "
                    //     sh 'kubectl apply -f kube/frontend-deployment.yml'
                    //     sh 'kubectl apply -f kube/frontend-service.yml'
                    //     sh 'kubectl apply -f kube/ingress.yml'
                    // }

                    deployToEks("${env.CLUSTER_CREDENTIALS}","${env.DEV_NS}","${params.Environment}")
                }
            }
        }

        stage("promote image DEV to QA"){
            when{
                expression{
                    params.Environment == "qa"
                }
            }
            steps{
                script{
                    // docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT}").pull()
                    // }

                    // sh "docker tag ${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}"

                    // docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}").push()
                    // }

                    promoteImage("${env.FRONTEND_IMAGE_DEV}","${env.FRONTEND_IMAGE_QA}","${env.DEV_DH_CREDENTIALS}","${env.QA_DH_CREDENTIALS}")

                    // withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-qa'){
                    //     sh 'echo deploying to employee-qa namespace...'
                    //     sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/frontend-deployment.yml "
                    //     sh 'kubectl apply -f kube/frontend-deployment.yml'
                    //     sh 'kubectl apply -f kube/frontend-service.yml'
                    //     sh 'kubectl apply -f kube/ingress.yml'
                    // }

                    deployToEks("${env.CLUSTER_CREDENTIALS}","${env.QA_NS}","${params.Environment}")
                }
            }
        }

        stage("promote image QA to UAT"){
            when {
                expression{
                    params.Environment == "uat"
                }
            }
            steps{
                script{
                    // docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}").pull()
                    // }

                    // sh "docker tag ${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}"

                    // docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}").push()
                    // }

                    promoteImage("${env.FRONTEND_IMAGE_QA}","${env.FRONTEND_IMAGE_UAT}","${env.QA_DH_CREDENTIALS}","${env.UAT_DH_CREDENTIALS}")

                    // withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-uat'){
                    //     sh 'echo deploying to employee-uat namespace...'
                    //     sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/frontend-deployment.yml "
                    //     sh 'kubectl apply -f kube/frontend-deployment.yml'
                    //     sh 'kubectl apply -f kube/frontend-service.yml'
                    //     sh 'kubectl apply -f kube/ingress.yml'
                    // }

                    deployToEks("${env.CLUSTER_CREDENTIALS}","${env.UAT_NS}","${params.Environment}")
                }
            }
        }

        stage("approval for prod"){
            when{
                expression{
                    params.Environment == 'prod'
                }
            }
            steps{
                input message: 'Promote the image from UAT to PROD?',
                      ok: "Promote to PROD"
            }
        }
        

        stage("Promote image from UAT to PROD"){
            when{
                expression{
                    params.Environment == "prod"
                }
            }
            steps{
                script{
                    // docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}").pull()
                    // }

                    // sh "docker tag ${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_PROD}:${GIT_COMMIT}"

                    // docker.withRegistry("${env.REGISTRY_URL}","${env.PROD_DH_CREDENTIALS}"){
                    //     docker.image("${env.FRONTEND_IMAGE_PROD}:${GIT_COMMIT}").push()
                    // }

                    promoteImage("${env.FRONTEND_IMAGE_UAT}","${env.FRONTEND_IMAGE_PROD}","${env.UAT_DH_CREDENTIALS}","${env.PROD_DH_CREDENTIALS}")


                    // withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-prod'){
                    //     sh 'echo deploying to employee-prod namespace...'
                    //     sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/frontend-deployment.yml "
                    //     sh 'kubectl apply -f kube/frontend-deployment.yml'
                    //     sh 'kubectl apply -f kube/frontend-service.yml'
                    //     sh 'kubectl apply -f kube/ingress.yml'
                    // }

                    deployToEks("${env.CLUSTER_CREDENTIALS}","${env.PROD_NS}","${params.Environment}")
                }
            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}