apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  namespace: ns-1
spec:
  nodeSelector:
    node-name: cloudethix-k8s-01
  containers:
    - name: pod-1-cont
      image: nginx
      ports:
        - containerPort: 80
