apiVersion: v1
kind: Pod
metadata:
  name: pod-0
  namespace: ns-1
spec:
  nodeSelector:
    node-name: cloudethix-k8s-00
  containers:
    - name: pod-0
      image: nginx
      ports:
        - containerPort: 80

