apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
  - name: app
    image: busybox
    command:
      - /bin/sh
      - -c
    args:
      - |
        echo "Hello from persistent storage" > /data/message.txt
        echo "Data written successfully"
        sleep 3600
    volumeMounts:
      - name: persistent-storage
        mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc

