apiVersion: v1
kind: Pod
metadata:
  name: secret-inspector
  namespace: ns-1
spec:
  containers:
    - name: secret-inspector
      image: avejlanjekar45/toolbox:1.0
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
      volumeMounts:
        - name: db-credential-volume
          mountPath: /etc/app/secrets
  volumes:
    - name: db-credential-volume
      secret:
        secretName: db-credentials
