apiVersion: v1
kind: Pod
metadata:
  name: config-inspector
  namespace: ns-1
spec:
  containers:
    - name: config-inspector
      image: avejlanjekar45/toolbox:1.0
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/app/config
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config 
