apiVersion: v1
kind: Pod
metadata:
  name: pod0
  namespace: ns-2
spec:
  nodeSelector:
    node-name: cloudethix-k8s-00
  containers:
    - name: pod0
      image: nginx
      ports:
        - containerPort: 80
