apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: ns-1
spec:
  containers:
    - name: pod-a
      image: avejlanjekar45/toolbox:1.0
      volumeMounts:
        - name: pv-storage
          mountPath: /data
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: shared-data
