apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudethix-configmap
  namespace: ns-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-webapp
  template:
    metadata:
      labels:
        app: frontend-webapp
    spec:
      containers:
        - name: cloudethix-cm
          image: avejlanjekar45/cloudethix_configmap_avej
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-config-map
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: frontend-config-map
          configMap:
            name: frontend-config
