apiVersion: v1
kind: Service
metadata:
  name: cloudethix-configmap-svc
  namespace: ns-1
spec:
  type: NodePort
  selector:
    app: frontend-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
