apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: ns-1
spec:
  containers:
    - name: pvc-test
      image: avejlanjekar45/toolbox:1.0
      volumeMounts:
        - name: pvc-storage
          mountPath: /data
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: shared-data
