apiVersion: v1
kind: Pod
metadata:
  name: secret-envfrom-pod
spec:
  containers:
  - name: secret-env-from-cont
    image: busybox
    command: ["/bin/sh" , "-c", "env"]
    env:
      envFrom:
      - secretKeyRef:
          name: secret-envfrom
