module "VPC" {
  source = "./modules/vpc"

  VPC_NAME             = var.VPC_NAME
  VPC_CIDR_BLOCK       = var.VPC_CIDR_BLOCK
  ENABLE_DNS_HOSTNAMES = var.ENABLE_DNS_HOSTNAMES
  ENABLE_DNS_SUPPORT   = var.ENABLE_DNS_SUPPORT
  VPC_COMMON_TAGS      = var.VPC_COMMON_TAGS

  IGW_NAME = var.IGW_NAME

  PUBLIC_SUBNET_CIDRS = var.PUBLIC_SUBNET_CIDRS
  APP_SUBNET_CIDRS    = var.APP_SUBNET_CIDRS
  DB_SUBNET_CIDRS     = var.DB_SUBNET_CIDRS

  AVAILABILITY_ZONES = var.AVAILABILITY_ZONES

  PUBLIC_SUBNET_NAME = var.PUBLIC_SUBNET_NAME
  APP_SUBNET_NAME    = var.APP_SUBNET_NAME
  DB_SUBNET_NAME     = var.DB_SUBNET_NAME

  EIP_NAME         = var.EIP_NAME
  NAT_GATEWAY_NAME = var.NAT_GATEWAY_NAME

  PUBLIC_ROUTE_CIDR  = var.PUBLIC_ROUTE_CIDR
  PRIVATE_ROUTE_CIDR = var.PRIVATE_ROUTE_CIDR

  PUBLIC_RT_NAME   = var.PUBLIC_RT_NAME
  PRIVATE_RT_NAME  = var.PRIVATE_RT_NAME
  DATABASE_RT_NAME = var.DATABASE_RT_NAME
}

module "SECURITY_GROUP" {
  source = "./modules/security-groups"

  VPC_ID = module.VPC.VPC_ID

  ALB_SECURITY_GROUP_NAME = var.ALB_SECURITY_GROUP_NAME
  ECS_SECURITY_GROUP_NAME = var.ECS_SECURITY_GROUP_NAME
  DB_SECURITY_GROUP_NAME  = var.DB_SECURITY_GROUP_NAME

  ALB_INGRESS_RULE = var.ALB_INGRESS_RULE
  ALB_EGRESS_RULE  = var.ALB_EGRESS_RULE

  ECS_INGRESS_RULES = var.ECS_INGRESS_RULES
  ECS_EGRESS_RULE   = var.ECS_EGRESS_RULE

  DB_INGRESS_RULE = var.DB_INGRESS_RULE
  DB_EGRESS_RULE  = var.DB_EGRESS_RULE

  COMMON_TAGS = var.VPC_COMMON_TAGS
}

module "ECR" {
  source = "./modules/ecr"

  BACKEND_REPOSITORY_NAME  = var.BACKEND_REPOSITORY_NAME
  FRONTEND_REPOSITORY_NAME = var.FRONTEND_REPOSITORY_NAME
  DATABASE_REPOSITORY_NAME = var.DATABASE_REPOSITORY_NAME

  IMAGE_TAG_MUTABILITY = var.IMAGE_TAG_MUTABILITY
  SCAN_ON_PUSH         = var.SCAN_ON_PUSH
  ENCRYPTION_TYPE      = var.ENCRYPTION_TYPE

  COMMON_TAGS = var.VPC_COMMON_TAGS
}

module "CLOUD_MAP" {
  source = "./modules/cloudmap"

  VPC_ID = module.VPC.VPC_ID

  NAMESPACE_NAME        = var.NAMESPACE_NAME
  NAMESPACE_DESCRIPTION = var.NAMESPACE_DESCRIPTION

  BACKEND_SERVICE_NAME  = var.BACKEND_CM_SERVICE_NAME
  FRONTEND_SERVICE_NAME = var.FRONTEND_CM__SERVICE_NAME
  DATABASE_SERVICE_NAME = var.DATABASE_CM_SERVICE_NAME

  DNS_RECORD_TYPE = var.DNS_RECORD_TYPE
  DNS_RECORD_TTL  = var.DNS_RECORD_TTL


  COMMON_TAGS = var.VPC_COMMON_TAGS
}

module "IAM" {
  source = "./modules/iam"

  ECS_TASK_EXECUTION_ROLE_NAME = var.ECS_TASK_EXECUTION_ROLE_NAME

  ECS_TASK_EXECUTION_POLICY_ARN = var.ECS_TASK_EXECUTION_POLICY_ARN

  COMMON_TAGS = var.VPC_COMMON_TAGS
}

# module "ECS" {
#   source = "./modules/ecs"

#   ECS_CLUSTER_NAME          = var.ECS_CLUSTER_NAME
#   ECS_CLUSTER_SETTING_NAME  = var.ECS_CLUSTER_SETTING_NAME
#   ECS_CLUSTER_SETTING_VALUE = var.ECS_CLUSTER_SETTING_VALUE

#   BACKEND_TASK_DEFINITION_FAMILY  = var.BACKEND_TASK_DEFINITION_FAMILY
#   FRONTEND_TASK_DEFINITION_FAMILY = var.FRONTEND_TASK_DEFINITION_FAMILY
#   DATABASE_TASK_DEFINITION_FAMILY = var.DATABASE_TASK_DEFINITION_FAMILY

#   BACKEND_CONTAINER_NAME  = var.BACKEND_CONTAINER_NAME
#   FRONTEND_CONTAINER_NAME = var.FRONTEND_CONTAINER_NAME
#   DATABASE_CONTAINER_NAME = var.DATABASE_CONTAINER_NAME

#   BACKEND_IMAGE  = var.BACKEND_IMAGE
#   FRONTEND_IMAGE = var.FRONTEND_IMAGE
#   DATABASE_IMAGE = var.DATABASE_IMAGE

#   ECS_TASK_EXECUTION_ROLE_ARN = module.IAM.ECS_TASK_EXECUTION_ROLE_ARN

#   ECS_TASK_CPU                 = var.ECS_TASK_CPU
#   ECS_TASK_MEMORY              = var.ECS_TASK_MEMORY
#   ECS_NETWORK_MODE             = var.ECS_NETWORK_MODE
#   ECS_REQUIRES_COMPATIBILITIES = var.ECS_REQUIRES_COMPATIBILITIES

#   BACKEND_CONTAINER_PORT  = var.BACKEND_CONTAINER_PORT
#   FRONTEND_CONTAINER_PORT = var.FRONTEND_CONTAINER_PORT
#   DATABASE_CONTAINER_PORT = var.DATABASE_CONTAINER_PORT

#   BACKEND_DB_NAME     = var.BACKEND_DB_NAME
#   BACKEND_DB_HOST     = var.BACKEND_DB_HOST
#   BACKEND_DB_PORT     = var.BACKEND_DB_PORT
#   BACKEND_DB_USER     = var.BACKEND_DB_USER
#   BACKEND_DB_PASSWORD = var.BACKEND_DB_PASSWORD

#   DATABASE_NAME          = var.DATABASE_NAME
#   DATABASE_ROOT_PASSWORD = var.DATABASE_ROOT_PASSWORD

#   FRONTEND_BACKEND_HOST = var.FRONTEND_BACKEND_HOST

#   BACKEND_LOG_GROUP_NAME  = var.BACKEND_LOG_GROUP_NAME
#   FRONTEND_LOG_GROUP_NAME = var.FRONTEND_LOG_GROUP_NAME
#   DATABASE_LOG_GROUP_NAME = var.DATABASE_LOG_GROUP_NAME

#   BACKEND_SERVICE_NAME  = var.BACKEND_SERVICE_NAME
#   FRONTEND_SERVICE_NAME = var.FRONTEND_SERVICE_NAME
#   DATABASE_SERVICE_NAME = var.DATABASE_SERVICE_NAME

#   ECS_SERVICE_DESIRED_COUNT = var.ECS_SERVICE_DESIRED_COUNT
#   ECS_LAUNCH_TYPE           = var.ECS_LAUNCH_TYPE
#   ECS_ASSIGN_PUBLIC_IP      = var.ECS_ASSIGN_PUBLIC_IP

#   ECS_APP_SUBNET_IDS = module.VPC.APP_SUBNET_IDS
#   ECS_DB_SUBNET_IDS  = module.VPC.DB_SUBNET_IDS

#   ECS_SECURITY_GROUP_ID = module.SECURITY_GROUP.ECS_SECURITY_GROUP_ID
#   DB_SECURITY_GROUP_ID  = module.SECURITY_GROUP.DB_SECURITY_GROUP_ID

#   BACKEND_TARGET_GROUP_ARN  = module.ALB.BACKEND_TARGET_GROUP_ARN
#   FRONTEND_TARGET_GROUP_ARN = module.ALB.FRONTEND_TARGET_GROUP_ARN

#   ENABLE_BACKEND_LOAD_BALANCER  = var.ENABLE_BACKEND_LOAD_BALANCER
#   ENABLE_FRONTEND_LOAD_BALANCER = var.ENABLE_FRONTEND_LOAD_BALANCER

#   BACKEND_CLOUD_MAP_SERVICE_ARN = module.CLOUD_MAP.BACKEND_SERVICE_ARN

#   FRONTEND_CLOUD_MAP_SERVICE_ARN = module.CLOUD_MAP.FRONTEND_SERVICE_ARN

#   DATABASE_CLOUD_MAP_SERVICE_ARN = module.CLOUD_MAP.DATABASE_SERVICE_ARN

#   AWS_REGION = var.AWS_REGION

#   COMMON_TAGS = var.VPC_COMMON_TAGS
# }

module "ECS_CLUSTER" {
  source = "./modules/ecs-cluster"

  ECS_CLUSTER_NAME          = var.ECS_CLUSTER_NAME
  ECS_CLUSTER_SETTING_NAME  = var.ECS_CLUSTER_SETTING_NAME
  ECS_CLUSTER_SETTING_VALUE = var.ECS_CLUSTER_SETTING_VALUE
  COMMON_TAGS               = var.COMMON_TAGS
}

module "ECS_TASK_DEFINITION" {
  source = "./modules/ecs-task-definition"

  BACKEND_TASK_DEFINITION_FAMILY  = var.BACKEND_TASK_DEFINITION_FAMILY
  FRONTEND_TASK_DEFINITION_FAMILY = var.FRONTEND_TASK_DEFINITION_FAMILY
  DATABASE_TASK_DEFINITION_FAMILY = var.DATABASE_TASK_DEFINITION_FAMILY

  ECS_NETWORK_MODE             = var.ECS_NETWORK_MODE
  ECS_REQUIRES_COMPATIBILITIES = var.ECS_REQUIRES_COMPATIBILITIES
  ECS_TASK_CPU                 = var.ECS_TASK_CPU
  ECS_TASK_MEMORY              = var.ECS_TASK_MEMORY
  ECS_TASK_EXECUTION_ROLE_ARN  = module.IAM.ECS_TASK_EXECUTION_ROLE_ARN

  BACKEND_CONTAINER_NAME = var.BACKEND_CONTAINER_NAME
  BACKEND_IMAGE          = var.BACKEND_IMAGE
  BACKEND_CONTAINER_PORT = var.BACKEND_CONTAINER_PORT
  BACKEND_DB_NAME        = var.BACKEND_DB_NAME
  BACKEND_DB_HOST        = var.BACKEND_DB_HOST
  BACKEND_DB_PORT        = var.BACKEND_DB_PORT
  BACKEND_DB_USER        = var.BACKEND_DB_USER
  BACKEND_DB_PASSWORD    = var.BACKEND_DB_PASSWORD
  BACKEND_LOG_GROUP_NAME = module.CLOUDWATCH.BACKEND_LOG_GROUP_NAME

  FRONTEND_CONTAINER_NAME = var.FRONTEND_CONTAINER_NAME
  FRONTEND_IMAGE          = var.FRONTEND_IMAGE
  FRONTEND_CONTAINER_PORT = var.FRONTEND_CONTAINER_PORT
  FRONTEND_BACKEND_HOST   = var.FRONTEND_BACKEND_HOST
  FRONTEND_LOG_GROUP_NAME = module.CLOUDWATCH.FRONTEND_LOG_GROUP_NAME

  DATABASE_CONTAINER_NAME = var.DATABASE_CONTAINER_NAME
  DATABASE_IMAGE          = var.DATABASE_IMAGE
  DATABASE_CONTAINER_PORT = var.DATABASE_CONTAINER_PORT
  DATABASE_NAME           = var.DATABASE_NAME
  DATABASE_ROOT_PASSWORD  = var.DATABASE_ROOT_PASSWORD
  DATABASE_LOG_GROUP_NAME = module.CLOUDWATCH.DATABASE_LOG_GROUP_NAME

  AWS_REGION = var.AWS_REGION
}


module "ECS_SERVICE" {
  source = "./modules/ecs-service"

  ECS_CLUSTER_ID = module.ECS_CLUSTER.ECS_CLUSTER_ID

  BACKEND_TASK_DEFINITION_ARN  = module.ECS_TASK_DEFINITION.BACKEND_TASK_DEFINITION_ARN
  FRONTEND_TASK_DEFINITION_ARN = module.ECS_TASK_DEFINITION.FRONTEND_TASK_DEFINITION_ARN
  DATABASE_TASK_DEFINITION_ARN = module.ECS_TASK_DEFINITION.DATABASE_TASK_DEFINITION_ARN

  BACKEND_SERVICE_NAME  = var.BACKEND_SERVICE_NAME
  FRONTEND_SERVICE_NAME = var.FRONTEND_SERVICE_NAME
  DATABASE_SERVICE_NAME = var.DATABASE_SERVICE_NAME

  ECS_SERVICE_DESIRED_COUNT = var.ECS_SERVICE_DESIRED_COUNT
  ECS_LAUNCH_TYPE           = var.ECS_LAUNCH_TYPE
  ECS_ASSIGN_PUBLIC_IP      = var.ECS_ASSIGN_PUBLIC_IP

  ECS_APP_SUBNET_IDS = module.VPC.APP_SUBNET_IDS
  ECS_DB_SUBNET_IDS  = module.VPC.DB_SUBNET_IDS

  ECS_SECURITY_GROUP_ID = module.SECURITY_GROUP.ECS_SECURITY_GROUP_ID
  DB_SECURITY_GROUP_ID  = module.SECURITY_GROUP.DB_SECURITY_GROUP_ID

  ENABLE_BACKEND_LOAD_BALANCER  = var.ENABLE_BACKEND_LOAD_BALANCER
  ENABLE_FRONTEND_LOAD_BALANCER = var.ENABLE_FRONTEND_LOAD_BALANCER

  BACKEND_TARGET_GROUP_ARN  = module.ALB.BACKEND_TARGET_GROUP_ARN
  FRONTEND_TARGET_GROUP_ARN = module.ALB.FRONTEND_TARGET_GROUP_ARN

  BACKEND_CONTAINER_NAME  = var.BACKEND_CONTAINER_NAME
  BACKEND_CONTAINER_PORT  = var.BACKEND_CONTAINER_PORT
  FRONTEND_CONTAINER_NAME = var.FRONTEND_CONTAINER_NAME
  FRONTEND_CONTAINER_PORT = var.FRONTEND_CONTAINER_PORT

  BACKEND_CLOUD_MAP_SERVICE_ARN  = module.CLOUD_MAP.BACKEND_SERVICE_ARN
  FRONTEND_CLOUD_MAP_SERVICE_ARN = module.CLOUD_MAP.FRONTEND_SERVICE_ARN
  DATABASE_CLOUD_MAP_SERVICE_ARN = module.CLOUD_MAP.DATABASE_SERVICE_ARN

  COMMON_TAGS = var.COMMON_TAGS
}



module "CLOUDWATCH" {
  source = "./modules/cloudwatch"

  BACKEND_LOG_GROUP_NAME  = var.BACKEND_LOG_GROUP_NAME
  FRONTEND_LOG_GROUP_NAME = var.FRONTEND_LOG_GROUP_NAME
  DATABASE_LOG_GROUP_NAME = var.DATABASE_LOG_GROUP_NAME

  LOG_GROUP_RETENTION_DAYS = var.LOG_GROUP_RETENTION_DAYS

  COMMON_TAGS = var.VPC_COMMON_TAGS
}

module "ALB" {
  source = "./modules/alb"

  ALB_NAME               = var.ALB_NAME
  ALB_INTERNAL           = var.ALB_INTERNAL
  ALB_LOAD_BALANCER_TYPE = var.ALB_LOAD_BALANCER_TYPE

  VPC_ID                = module.VPC.VPC_ID
  ALB_SUBNET_IDS        = module.VPC.PUBLIC_SUBNET_IDS
  ALB_SECURITY_GROUP_ID = module.SECURITY_GROUP.ALB_SECURITY_GROUP_ID

  BACKEND_TARGET_GROUP_NAME     = var.BACKEND_TARGET_GROUP_NAME
  BACKEND_TARGET_GROUP_PORT     = var.BACKEND_TARGET_GROUP_PORT
  BACKEND_TARGET_GROUP_PROTOCOL = var.BACKEND_TARGET_GROUP_PROTOCOL
  BACKEND_TARGET_TYPE           = var.BACKEND_TARGET_TYPE
  BACKEND_HEALTH_CHECK_PATH     = var.BACKEND_HEALTH_CHECK_PATH
  BACKEND_HEALTH_CHECK_PORT     = var.BACKEND_HEALTH_CHECK_PORT

  FRONTEND_TARGET_GROUP_NAME     = var.FRONTEND_TARGET_GROUP_NAME
  FRONTEND_TARGET_GROUP_PORT     = var.FRONTEND_TARGET_GROUP_PORT
  FRONTEND_TARGET_GROUP_PROTOCOL = var.FRONTEND_TARGET_GROUP_PROTOCOL
  FRONTEND_TARGET_TYPE           = var.FRONTEND_TARGET_TYPE
  FRONTEND_HEALTH_CHECK_PATH     = var.FRONTEND_HEALTH_CHECK_PATH
  FRONTEND_HEALTH_CHECK_PORT     = var.FRONTEND_HEALTH_CHECK_PORT

  ALB_LISTENER_PORT     = var.ALB_LISTENER_PORT
  ALB_LISTENER_PROTOCOL = var.ALB_LISTENER_PROTOCOL

  COMMON_TAGS = var.VPC_COMMON_TAGS
}