apiVersion: v1
kind: Pod
metadata:
  name: secret-subpath
  namespace: ns-1
spec:
  containers:
    - name: secret-subpath
      image: avejlanjekar45/toolbox:1.0
      volumeMounts:
        - name: secret-subpath-volume
          mountPath: /etc/app/secret-password
          subPath: password
  volumes:
    - name: secret-subpath-volume
      secret:
        secretName: db-credentials
        defaultMode: 0400
