apiVersion: v1
kind: Pod
metadata:
  name: inventory-service
  namespace: ns-1
  labels:
    app: inventory-service
spec:
  containers:
    - name: inventory-service
      image: avejlanjekar45/inventory-service:1.0
      ports:
        - containerPort: 5678 
      volumeMounts:
        - name: inventory-pv
          mountPath: /etc/app/config
  volumes:
    - name: inventory-pv
      configMap:
        name: app-config
