apiVersion: v1
kind: Pod
metadata:
  name: secret-from-volume-pod
spec:
  containers:
  - name: secret-from-volume-cont
    image: busybox
    command:
    - /bin/sh
    - -c
    args:
    - |
      echo "Container is running"
      sleep 3600
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
  
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-from-volume
