apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
  MYSQL_DATABASE: ZW1wbG95ZWVfZGI=
  MYSQL_USER: ZW1wbG95ZWVfdXNlcg==
  MYSQL_PASSWORD: ZW1wbG95ZWUxMjM=
