apiVersion: v1
kind: Service
metadata:
  name: frontend-webapp-svc
  namespace: ns-2
spec:
  type: NodePort
  selector:
    app: frontend-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
