apiVersion: v1
kind: Pod
metadata:
  name: config-subpath
  namespace: ns-1
spec:
  containers:
    - name: config-subpath
      image: avejlanjekar45/toolbox:1.0
      volumeMounts:
        - name: config-subpath-volume
          subPath: APP_NAME
          mountPath: /etc/app/name.txt
  volumes:
    - name: config-subpath-volume
      configMap:
        name: app-config
